#!/usr/bin/env bash

# You will need to have generated a gpg (pgp) key prior to running this script.
# Generate the private gpg key somewhere else safe, or on a liveboot image.
# Then bring over the public key to a file called pub.asc
# Import pub.asc into user keyring and then call the moat-encrypt script like this:

# ./moat-encrypt somefile.tbin adminbobperson@something.place.example.com

# osenc my-secretfile.txt mysecretfile.txt.asc
moatenc-file () {
  gpg --batch --yes --passphrase-fd 0 -r $2 -e $1
}

# If you don't have the shred program, do some overwriting at least...
shredda () {
shredd=$(which shred)
if [ $shredd -z ]; then
   openssl rand -base64 900000 > $target
   echo 0 > $target
   cp /dev/null $target
else
  shred -v -n 25 -u -z $target
fi
}

# encrypt your first argument with the public key identified with the second argument
moatenc-file $1 $2

# Wipe out your copy of original file.
target=$1
shredda

rm -f $1 2>/dev/null
